### ISSUE TITLE
iOS18微信显示有BUG

### ISSUE THREAD

**Issue by Nihility-Ming** [ccnhm/car-number-keyboard#1]
在最新版本的iOS18的微信下，用该组件库会出现蓝色闪烁线长显示的BUG

**Comment by Nihility-Ming** [comment]
![Uploading image_2024-09-22_19-40-21.jpg…]()

**Comment by Nihility-Ming** [comment]
![image_2024-09-22_19-40-21](https://github.com/user-attachments/assets/17202696-3526-46b1-8155-710d79800071)

**Comment by ccnhm** [comment]
已修复
